import io.vertx.core.Vertx
import io.vertx.jdbcclient.JDBCConnectOptions
import io.vertx.jdbcclient.JDBCPool
import io.vertx.kotlin.coroutines.coAwait
import io.vertx.sqlclient.Pool
import io.vertx.sqlclient.PoolOptions
import java.nio.file.Files
import java.nio.file.Path
import java.util.Properties

enum class DbAuthMode {
    SQL,
    INTEGRATED
}

data class DbConfig(
    val host: String,
    val port: Int,
    val database: String,
    val user: String,
    val password: String,
    val trustServerCertificate: Boolean,
    val encrypt: Boolean,
    val authMode: DbAuthMode,
    val connectionString: String?
) {
    companion object {
        fun fromEnv(env: Map<String, String>): DbConfig {
            val fileProps = loadDbProperties()
            val connectionString = firstNonBlank(env["DB_CONNECTION_STRING"], fileProps.getProperty("db.connectionString"))
            val host = firstNonBlank(env["DB_HOST"], fileProps.getProperty("db.host")) ?: "DESKTOP-6CEGSEJ"
            val port = (firstNonBlank(env["DB_PORT"], fileProps.getProperty("db.port"))?.toIntOrNull() ?: 1433)
            val database = firstNonBlank(env["DB_NAME"], fileProps.getProperty("db.name")) ?: "SoapProduction"
            val user = firstNonBlank(env["DB_USER"], fileProps.getProperty("db.user")) ?: ""
            val password = firstNonBlank(env["DB_PASSWORD"], fileProps.getProperty("db.password")) ?: ""
            val trust = firstNonBlank(env["DB_TRUST_SERVER_CERT"], fileProps.getProperty("db.trustServerCertificate"))
                ?.toBooleanStrictOrNull() ?: true
            val encrypt = firstNonBlank(env["DB_ENCRYPT"], fileProps.getProperty("db.encrypt"))
                ?.toBooleanStrictOrNull() ?: true
            val authMode = when (firstNonBlank(env["DB_AUTH"], fileProps.getProperty("db.auth"))?.lowercase()) {
                "integrated", "windows", "ia" -> DbAuthMode.INTEGRATED
                else -> DbAuthMode.SQL
            }

            if (connectionString == null && authMode == DbAuthMode.SQL) {
                require(user.isNotBlank()) {
                    "DB_USER is required. Set DB_USER/DB_PASSWORD for SQL Server login."
                }
            }

            return DbConfig(host, port, database, user, password, trust, encrypt, authMode, connectionString)
        }

        private fun loadDbProperties(): Properties {
            val props = Properties()
            val path = Path.of("db.properties")
            if (Files.exists(path)) {
                Files.newInputStream(path).use { props.load(it) }
            }
            return props
        }

        private fun firstNonBlank(vararg values: String?): String? {
            for (value in values) {
                if (!value.isNullOrBlank()) return value
            }
            return null
        }
    }
}

class DbClient(val pool: Pool) {
    companion object {
        fun fromEnv(vertx: Vertx): DbClient {
            val config = DbConfig.fromEnv(System.getenv())
            if (config.connectionString != null) {
                val connectOptions = JDBCConnectOptions()
                    .setJdbcUrl(config.connectionString)
                    .setAutoGeneratedKeys(false)
                return DbClient(JDBCPool.pool(vertx, connectOptions, PoolOptions()))
            }
            val url = buildString {
                append("jdbc:sqlserver://")
                append(config.host)
                append(":")
                append(config.port)
                append(";databaseName=")
                append(config.database)
                when (config.authMode) {
                    DbAuthMode.SQL -> {
                        append(";user=")
                        append(config.user)
                        append(";password=")
                        append(config.password)
                    }
                    DbAuthMode.INTEGRATED -> {
                        append(";integratedSecurity=true")
                    }
                }
                append(";encrypt=")
                append(config.encrypt)
                append(";trustServerCertificate=")
                append(config.trustServerCertificate)
            }
            val connectOptions = JDBCConnectOptions()
                .setJdbcUrl(url)
                .setAutoGeneratedKeys(false)
            return DbClient(JDBCPool.pool(vertx, connectOptions, PoolOptions()))
        }
    }

    suspend fun close() {
        pool.close().coAwait()
    }
}
