package config

import io.vertx.core.Vertx
import io.vertx.jdbcclient.JDBCConnectOptions
import io.vertx.jdbcclient.JDBCPool
import io.vertx.kotlin.coroutines.coAwait
import io.vertx.sqlclient.Pool
import io.vertx.sqlclient.PoolOptions

class DbClient(val pool: Pool) {
    companion object {
        fun fromEnv(vertx: Vertx): DbClient {
            val config = DbConfig.fromEnv(System.getenv())
            if (config.connectionString != null) {
                val opts = JDBCConnectOptions().setJdbcUrl(config.connectionString).setAutoGeneratedKeys(false)
                return DbClient(JDBCPool.pool(vertx, opts, PoolOptions()))
            }
            val url = buildString {
                append("jdbc:sqlserver://${config.host}:${config.port};databaseName=${config.database}")
                when (config.authMode) {
                    DbAuthMode.SQL -> append(";user=${config.user};password=${config.password}")
                    DbAuthMode.INTEGRATED -> append(";integratedSecurity=true")
                }
                append(";encrypt=${config.encrypt};trustServerCertificate=${config.trustServerCertificate}")
            }
            val opts = JDBCConnectOptions().setJdbcUrl(url).setAutoGeneratedKeys(false)
            return DbClient(JDBCPool.pool(vertx, opts, PoolOptions()))
        }
    }

    suspend fun close() { pool.close().coAwait() }
}
